In [1]:
import numpy as np

In [14]:
a = np.array([[0.00000, 0.25000, 0.25000, 0.25000, 0.25000, 0.00000],
[0.00000, 0.00000, 0.25000, 0.25000, 0.25000, 0.25000],
[0.00000, 0.00000, 0.00000, 0.25000, 0.25000, 0.50000],
[0.00000, 0.00000, 0.00000, 0.00000, 0.25000, 0.75000],
[0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000],
[0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000]])
a

array([[0.  , 0.25, 0.25, 0.25, 0.25, 0.  ],
       [0.  , 0.  , 0.25, 0.25, 0.25, 0.25],
       [0.  , 0.  , 0.  , 0.25, 0.25, 0.5 ],
       [0.  , 0.  , 0.  , 0.  , 0.25, 0.75],
       [0.  , 0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 1.  ]])

In [15]:
A = np.array(a)
for i in range(100):
    A = A @ a
    print(A)

[[0.     0.     0.0625 0.125  0.4375 0.375 ]
 [0.     0.     0.     0.0625 0.375  0.5625]
 [0.     0.     0.     0.     0.3125 0.6875]
 [0.     0.     0.     0.     0.25   0.75  ]
 [0.     0.     0.     0.     1.     0.    ]
 [0.     0.     0.     0.     0.     1.    ]]
[[0.       0.       0.       0.015625 0.484375 0.5     ]
 [0.       0.       0.       0.       0.390625 0.609375]
 [0.       0.       0.       0.       0.3125   0.6875  ]
 [0.       0.       0.       0.       0.25     0.75    ]
 [0.       0.       0.       0.       1.       0.      ]
 [0.       0.       0.       0.       0.       1.      ]]
[[0.         0.         0.         0.         0.48828125 0.51171875]
 [0.         0.         0.         0.         0.390625   0.609375  ]
 [0.         0.         0.         0.         0.3125     0.6875    ]
 [0.         0.         0.         0.         0.25       0.75      ]
 [0.         0.         0.         0.         1.         0.        ]
 [0.         0.         0.         0.    

In [17]:
b = np.array([[0.00000, 0.25000, 0.25000, 0.25000, 0.25000, 0.00000],
[0.00000, 0.00000, 0.25000, 0.25000, 0.25000, 0.25000],
[0.00000, 0.00000, 0.00000, 0.25000, 0.25000, 0.50000],
[0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000],
[0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000],
[0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000]])
b

array([[0.  , 0.25, 0.25, 0.25, 0.25, 0.  ],
       [0.  , 0.  , 0.25, 0.25, 0.25, 0.25],
       [0.  , 0.  , 0.  , 0.25, 0.25, 0.5 ],
       [0.  , 0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 1.  ]])

In [18]:
B = np.array(b)
for i in range(100):
    B = B @ b
    print(B)

[[0.     0.     0.0625 0.375  0.375  0.1875]
 [0.     0.     0.     0.3125 0.3125 0.375 ]
 [0.     0.     0.     0.25   0.25   0.5   ]
 [0.     0.     0.     1.     0.     0.    ]
 [0.     0.     0.     0.     1.     0.    ]
 [0.     0.     0.     0.     0.     1.    ]]
[[0.       0.       0.       0.390625 0.390625 0.21875 ]
 [0.       0.       0.       0.3125   0.3125   0.375   ]
 [0.       0.       0.       0.25     0.25     0.5     ]
 [0.       0.       0.       1.       0.       0.      ]
 [0.       0.       0.       0.       1.       0.      ]
 [0.       0.       0.       0.       0.       1.      ]]
[[0.       0.       0.       0.390625 0.390625 0.21875 ]
 [0.       0.       0.       0.3125   0.3125   0.375   ]
 [0.       0.       0.       0.25     0.25     0.5     ]
 [0.       0.       0.       1.       0.       0.      ]
 [0.       0.       0.       0.       1.       0.      ]
 [0.       0.       0.       0.       0.       1.      ]]
[[0.       0.       0.       0.390625 0.390

In [ ]:
## Programming Assignment

In [ ]:
from random import randrange

In [20]:
def getState(hand):
    return sum(hand)

def resetHand(hand):
    hand = []

def drawCardForHand(hand):
    hand.append(int(randrange(4)))

In [ ]:
hand = []

transition_matrix = []

for i in range(1,5):
    

