In [1]:
import numpy as np

# 1

## B. Whitejack

### a.

In [39]:
a = np.array([[0.00000, 0.25000, 0.25000, 0.25000, 0.25000, 0.00000],
[0.00000, 0.00000, 0.25000, 0.25000, 0.25000, 0.25000],
[0.00000, 0.00000, 0.00000, 0.25000, 0.25000, 0.50000],
[0.00000, 0.00000, 0.00000, 0.00000, 0.25000, 0.75000],
[0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000],
[0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000]])
a

array([[0.  , 0.25, 0.25, 0.25, 0.25, 0.  ],
       [0.  , 0.  , 0.25, 0.25, 0.25, 0.25],
       [0.  , 0.  , 0.  , 0.25, 0.25, 0.5 ],
       [0.  , 0.  , 0.  , 0.  , 0.25, 0.75],
       [0.  , 0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 1.  ]])

In [43]:
A = np.array(a)
Pinf = 0
for i in range(100):
    A = A @ a
    Pinf = A
print(Pinf)

[[0.         0.         0.         0.         0.48828125 0.51171875]
 [0.         0.         0.         0.         0.390625   0.609375  ]
 [0.         0.         0.         0.         0.3125     0.6875    ]
 [0.         0.         0.         0.         0.25       0.75      ]
 [0.         0.         0.         0.         1.         0.        ]
 [0.         0.         0.         0.         0.         1.        ]]


### c.

In [45]:
c = np.array([[0.00000, 0.25000, 0.25000, 0.25000, 0.25000, 0.00000],
[0.00000, 0.00000, 0.25000, 0.25000, 0.25000, 0.25000],
[0.00000, 0.00000, 0.00000, 0.25000, 0.25000, 0.50000],
[0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000],
[0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000],
[0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000]])
c

array([[0.  , 0.25, 0.25, 0.25, 0.25, 0.  ],
       [0.  , 0.  , 0.25, 0.25, 0.25, 0.25],
       [0.  , 0.  , 0.  , 0.25, 0.25, 0.5 ],
       [0.  , 0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 1.  ]])

In [46]:
C = np.array(c)
Pinf = 0
for i in range(100):
    C = C @ c
    Pinf = C
print(Pinf)

[[0.       0.       0.       0.390625 0.390625 0.21875 ]
 [0.       0.       0.       0.3125   0.3125   0.375   ]
 [0.       0.       0.       0.25     0.25     0.5     ]
 [0.       0.       0.       1.       0.       0.      ]
 [0.       0.       0.       0.       1.       0.      ]
 [0.       0.       0.       0.       0.       1.      ]]


## C. Grayjack

## D. Programming Assignment

### A.

In [26]:
from random import randrange

In [20]:
def getState(hand):
    return sum(hand)

def resetHand(hand):
    hand = []

def drawCardForHand(hand):
    hand.(int(randrange(4)))

[]

In [58]:
hand = 0

matrix = []

for i in range(0,6):  # 0 is start and 5 is bust
    st, s1, s2, s3, s4, bs, nt = 0, 0, 0, 0, 0, 0, 100
    for r in range(nt):
        hand = 0
        hand += i
        hand = hand + int(randrange(1,5)) # draw card
        if hand == 0:
            st += 1
        elif hand == 1:
            s1 += 1
        elif hand == 2:
            s2 += 1
        elif hand == 3:
            s3 += 1
        elif hand == 4:
            s4 += 1
        elif hand >= 5:
            bs += 1
        else:
            print('You\'re not supposed to reach here.')
    matrix.append([st/nt, s1/nt, s2/nt, s3/nt, s4/nt, bs/nt])
#     matrix.append([st, s1, s2, s3, s4, bs])

matrix        

[[0.0, 0.28, 0.25, 0.24, 0.23, 0.0],
 [0.0, 0.0, 0.2, 0.3, 0.24, 0.26],
 [0.0, 0.0, 0.0, 0.26, 0.23, 0.51],
 [0.0, 0.0, 0.0, 0.0, 0.2, 0.8],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]