In [13]:
from sklearn import datasets
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import random
import numpy as np

In [2]:
#1
iris = datasets.load_iris()
X = iris.data[:, :2]
y = (iris.target != 0) * 1

In [4]:
#2
X_std = preprocessing.scale(X)
X

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.6],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [9]:
#3
theta = []
for i in range(3):
    theta.append(random.uniform(-1,1))
theta = np.array(theta)
theta

array([0.37521549, 0.10929227, 0.31218768])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

array([[6.1, 2.8],
       [5.7, 3.8],
       [7.7, 2.6],
       [6. , 2.9],
       [6.8, 2.8],
       [5.4, 3.4],
       [5.6, 2.9],
       [6.9, 3.1],
       [6.2, 2.2],
       [5.8, 2.7],
       [6.5, 3.2],
       [4.8, 3. ],
       [5.5, 3.5],
       [4.9, 3.1],
       [5.1, 3.8],
       [6.3, 3.3],
       [6.5, 3. ],
       [5.6, 2.5],
       [5.7, 2.8],
       [6.4, 2.8],
       [4.7, 3.2],
       [6.1, 3. ],
       [5. , 3.4],
       [6.4, 2.8],
       [7.9, 3.8],
       [6.7, 3. ],
       [6.7, 2.5],
       [6.8, 3.2],
       [4.8, 3. ],
       [4.8, 3.1],
       [4.6, 3.6],
       [5.7, 4.4],
       [6.7, 3.1],
       [4.8, 3.4],
       [4.4, 3.2],
       [6.3, 2.5],
       [6.4, 3.2],
       [5.2, 3.5],
       [5. , 3.6],
       [5.2, 4.1],
       [5.8, 2.7],
       [6. , 3.4],
       [6.7, 3.1],
       [5.4, 3.9],
       [5.4, 3.7],
       [5.5, 2.4],
       [6.3, 2.8],
       [6.4, 3.1],
       [6.6, 3. ],
       [7.2, 3.6]])